function manifest = tbxManifest()
%TBXMANIFEST Dependency manifest of the Loudspeaker System Toolbox.
%   manifest = tbxManifest() returns what ships in the .mltbx, what the toolbox needs at runtime and what is left out,
%   from the dependency analysis of phase 2 of the packaging pipeline (2026-10-01). The toolbox needs MATLAB only: no
%   other MathWorks product, no add-on and no file outside the toolbox folder.

    manifest.generated = "2026-10-01";
    manifest.toolbox_root = fullfile(fileparts(fileparts(mfilename("fullpath"))),"toolbox");

    % Files shipping in the .mltbx: the effective file set of the toolbox folder, without the files in
    % manifest.excluded, relative to the toolbox folder
    manifest.included = { ...
        "+comp/@ClosedBox/ClosedBox.m"; ...
        "+comp/@Driver/Driver.m"; ...
        "+comp/@Enclosure/Enclosure.m"; ...
        "+comp/@FeaEnclosure/FeaEnclosure.m"; ...
        "@lspsys/lspsys.m"; ...
        "@result/result.m"; ...
        "doc/GettingStarted.m"; ...
        "doc/comp/closedbox/closedboxdoc.m"; ...
        "doc/comp/closedbox/helperfiles/closedboxfourports.png"; ...
        "doc/comp/closedbox/helperfiles/closedboxfourports.svg"; ...
        "doc/comp/driver/driverdoc.m"; ...
        "doc/comp/driver/methods/tbldoc/tbldoc.m"; ...
        "doc/comp/driver/methods/tedoc/tedoc.m"; ...
        "doc/comp/driver/methods/tmdoc/tmdoc.m"; ...
        "doc/comp/driver/methods/tsddoc/tsddoc.m"; ...
        "doc/comp/driver/methods/zebdoc/zebdoc.m"; ...
        "doc/comp/driver/methods/zmdoc/zmdoc.m"; ...
        "doc/comp/enclosure/enclosuredoc.m"; ...
        "doc/comp/enclosure/helperfiles/enclosurefourports.png"; ...
        "doc/comp/enclosure/helperfiles/enclosurefourports.svg"; ...
        "doc/comp/feaenclosure/feaenclosuredoc.m"; ...
        "doc/comp/feaenclosure/helperfiles/feaenclosurefourports.png"; ...
        "doc/comp/feaenclosure/helperfiles/feaenclosurefourports.svg"; ...
        "doc/lspsys/helperfiles/classdiagram.png"; ...
        "doc/lspsys/helperfiles/classdiagram.svg"; ...
        "doc/lspsys/helperfiles/classdiagramcollapsed.png"; ...
        "doc/lspsys/helperfiles/classdiagramcollapsed.svg"; ...
        "doc/lspsys/helperfiles/lspsyssequencediagram.svg"; ...
        "doc/lspsys/lspsysdoc.m"; ...
        "doc/lspsys/methods/createresultdoc/createresultdoc.m"; ...
        "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/networkdiagramdefinition.png"; ...
        "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/networkdiagramdefinition.svg"; ...
        "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/networkdiagramfourport.png"; ...
        "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/networkdiagramfourport.svg"; ...
        "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/networkdiagramfourportdetail.png"; ...
        "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/networkdiagramfourportdetail.svg"; ...
        "doc/lspsys/methods/solve2portnetworkdoc/solve2portnetworkdoc.m"; ...
        "doc/overview.m"; ...
        "doc/result/methods/plotdoc/plotdoc.m"; ...
        "doc/result/methods/splexcursionlimiteddoc/splexcursionlimiteddoc.m"; ...
        "doc/result/methods/splmaxdoc/splmaxdoc.m"; ...
        "doc/result/methods/splmaxpeakvoltagedoc/splmaxpeakvoltagedoc.m"; ...
        "doc/result/methods/splpowerlimiteddoc/splpowerlimiteddoc.m"; ...
        "doc/result/resultdoc.m"; ...
        "doc/symbols.m"; ...
        "examples/closedBoxExample.m"; ...
        "examples/demos.xml"; ...
        "examples/feaEnclosureExample.m"; ...
        "examples/helperfiles/feaexample_pfront.txt"; ...
        "examples/helperfiles/feaexample_prear.txt"; ...
        "examples/helperfiles/feaexample_prmic.txt"; ...
        "resources/functionSignatures.json"; ...
    };

    % MathWorks product requirements: MATLAB itself only (requiredFilesAndProducts, Certain = 1)
    manifest.products = {};

    % Add-on dependencies
    manifest.addons = {};

    % Resolved externals (user-approved actions taken): there are no files outside the toolbox that the code needs
    manifest.resolved = {};

    % Unresolved externals
    manifest.unresolved = {};

    % Ignore file conflicts: no file that the code needs is excluded
    manifest.ignore_conflicts = {};

    % Files inside the toolbox folder that do not ship (decided by the user in phase 1); they go in the ignore file
    manifest.excluded = { ...
        struct("files", {{"doc/lspsys/helperfiles/generateclassdiagramsvg.m", ...
                          "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/generatenetworkdiagramsvg.m"}}, ...
               "reason", "Development tools that generate the diagram SVG files; the network diagram generator " + ...
                         "uses Chrome and matlabroot"); ...
        struct("files", {{"doc/lspsys/methods/solve2portnetworkdoc/helperfiles/ac_voltage.svg", ...
                          "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/capacitor.svg", ...
                          "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/gyrator.svg", ...
                          "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/ideal_transformer.svg", ...
                          "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/inductor.svg", ...
                          "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/open_circuit.svg", ...
                          "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/reference.svg", ...
                          "doc/lspsys/methods/solve2portnetworkdoc/helperfiles/resistor.svg"}}, ...
               "reason", "Copies of Simscape Foundation library icons, used by the diagram generator only; " + ...
                         "redistribution not cleared"); ...
        struct("files", {{"doc/lspsys/helperfiles/classdiagram.mldatx"}}, ...
               "reason", "Source of the class diagram for the Class Diagram Viewer; the documentation uses the " + ...
                         "PNG and SVG files"); ...
    };

    % Runtime file references
    manifest.runtime_files = { ...
        struct("file", "+comp/@FeaEnclosure/FeaEnclosure.m", ...
               "reads", "Ansys result files of the user, given by name in PressureFrontFileName, " + ...
                        "PressureRearFileName and PressureFarFieldFileName", ...
               "notes", "The examples and the documentation use examples/helperfiles/feaexample_*.txt by name, " + ...
                        "so that folder must be on the MATLAB path after the installation"); ...
    };

    % Advice for the build plan (phase 5): put only these two folders on the MATLAB path with
    % ToolboxOptions.ToolboxMatlabPath. The default adds all 46 subfolders, so that generic names such as overview.m,
    % symbols.m and GettingStarted.m land on the path of the user. The documentation links use which('lspsys') and
    % need no path.
    manifest.matlab_path = ["toolbox", "toolbox/examples/helperfiles"];
end
