function spec = toolboxSpecification()
%toolboxSpecification Interface specification for the Loudspeaker System Toolbox.
%   spec = toolboxSpecification() returns the toolbox interface spec as a struct: the public API of the toolbox, which
%   is what the users may use and what is kept stable between versions: the public properties and methods of the
%   classes. Phase 6 of the packaging pipeline compares the code with this spec.

    spec.toolbox.name = "Loudspeaker System Toolbox";
    spec.toolbox.version = "0.1.0";
    spec.toolbox.summary = "Model and simulate loudspeaker systems in the frequency domain.";
    spec.toolbox.purpose = "Modeling and simulating loudspeaker systems, with a variety in enclosure types.";
    spec.toolbox.sourcePath = "toolbox";

    % Cell array: the entries are classes, which carry the fields methods and properties
    spec.entries = { ...
        struct("function", "lspsys", "file", "@lspsys/lspsys.m", ...
               "signature", "obj = lspsys", ...
               "h1", "Loudspeaker system object", "category", "System", ...
               "visibility", "public", "type", "classdef", ...
               "methods", {{"createResult", "solve2PortNetwork", "f2k", "f2Lambda"}}, ...
               "properties", {{"Frequency", "SourceVoltage", "RadiationAngle", "Enclosure", "AngularFrequency", ...
                               "WaveNumber", "Wavelength", "NumFrequencies", "SpeedOfSound", "AirDensity", ...
                               "ReferencePressure"}}); ...
        struct("function", "result", "file", "@result/result.m", ...
               "signature", "obj = result", ...
               "h1", "Results of a loudspeaker system calculation", "category", "Results", ...
               "visibility", "public", "type", "classdef", ...
               "methods", {{"plot", "splMax", "splPowerLimited", "splExcursionLimited", "splMaxPeakVoltage"}}, ...
               "properties", {{"Frequency", "SourceVoltage", "SourceCurrent", "DiaphragmVolumeVelocity", ...
                               "RadiatedVolumeVelocity", "RadiationAngle", "MicTransfer", "Driver", "MicRadius", ...
                               "ExcursionLimit", "PowerLimit", "ElectricalImpedance", "Pressure", ...
                               "SoundPressureLevel", "DiaphragmExcursion", "DiaphragmPeakExcursion"}}); ...
        struct("function", "comp.Driver", "file", "+comp/@Driver/Driver.m", ...
               "signature", "obj = comp.Driver", ...
               "h1", "Class definition for a loudspeaker driver", "category", "Components: drivers", ...
               "visibility", "public", "type", "classdef", ...
               "methods", {{"zeb", "zm", "te", "tbl", "tm", "tsd"}}, ...
               "properties", {{"Re", "Le", "Qes", "Qms", "Fs", "Sd", "Vas", "Znom", "Zmin", "Pnom", "Pcont", ...
                               "Paes1984", "Paes2012", "Xmax", "Xvar", "Xlim", "Xmech", "ExcursionLimit", ...
                               "PowerLimit", "Bl", "Cms", "Mmd", "Mms", "Mmi", "Rms", "DiaphragmRadius", ...
                               "Qts"}}); ...
        struct("function", "comp.Enclosure", "file", "+comp/@Enclosure/Enclosure.m", ...
               "signature", "obj = comp.Enclosure (abstract: create a subclass)", ...
               "h1", "Base class for the enclosure of a loudspeaker driver", "category", "Components: enclosures", ...
               "visibility", "public", "type", "classdef", ...
               "methods", {{"tae", "tarad", "zaFront", "zaRear", "micTransfer", "zarad", "struve"}}, ...
               "properties", {{"Driver"}}); ...
        struct("function", "comp.ClosedBox", "file", "+comp/@ClosedBox/ClosedBox.m", ...
               "signature", "obj = comp.ClosedBox", ...
               "h1", "Closed-box enclosure of a loudspeaker driver", "category", "Components: enclosures", ...
               "visibility", "public", "type", "classdef", ...
               "methods", {{"tae", "tarad"}}, ...
               "properties", {{"RearVolume"}}); ...
        struct("function", "comp.FeaEnclosure", "file", "+comp/@FeaEnclosure/FeaEnclosure.m", ...
               "signature", "obj = comp.FeaEnclosure", ...
               "h1", "Enclosure described by the results of an FEA model in Ansys", ...
               "category", "Components: enclosures", ...
               "visibility", "public", "type", "classdef", ...
               "methods", {{"tae", "tarad", "micTransfer", "importAnsysPressureResults"}}, ...
               "properties", {{"DiaphragmVelocity", "PressureFrontFileName", "PressureRearFileName", ...
                               "PressureFarFieldFileName", "VolumeVelocity", "Frequency"}}); ...
    };
end
